### ISSUE TITLE
Running part find_genetrees_local.sh

### ISSUE THREAD

**Issue by GabiCamacho** [MikeWLloyd/PartitionedGeneTree#2]
There was a few things that I changed to get it to run locally, I thought I could share! 

#This was reading argument 3 (swscen) and not 4 (number of threads), so I changed for $4
re='^[0-9]+$'
if ! [[ $4 =~ $re ]] ; then
   echo "error: you provided something other than a number for threads" >&2; exit 1
fi

#SWSC-EN was not reading the name of the file properly, so I added $locus to the .nexus file.
eval python $swscen $ARQ$locus.nexus

#rename was not running on my machine, so I changed for mv and remove the comma between the arguments
 mv $ARQ/$locus.nexus_entropy_partition_finder.cfg $ARQ/partition_finder.cfg

**Comment by MikeWLloyd** [comment]
Fixed in commit 9883c76. Check that I corrected the code correctly.
